language: cpp

compiler:
 - gcc
 - clang

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev libqt5test5
 - sudo apt-get install qt5-default qttools5-dev-tools
 - sudo apt-get install libudunits2-dev
 - sudo pip install cpp-coveralls

script:
 - qmake
 - make -j$(nproc)

after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
