language: cpp

compiler:
 - gcc

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev libqt5test5 qt5-default qttools5-dev-tools libudunits2-dev lcov 
 - sudo pip install cpp-coveralls

script:
 - ./bin/travis.sh

after_success:
  - cpp-coveralls -n -e /usr/include
